language: php

php:
  - 7.0

install:
  - composer self-update
  - composer require --dev codeception/codeception

script:
  - php vendor/bin/codecept run unit models

before_deploy:
  - .travis/set-up-ssh.sh

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master