language: php

php:
  - 7.0

install:
  - composer global require "fxp/composer-asset-plugin:~1.3"
  - composer update

script:
  - php vendor/bin/codecept run unit models

before_deploy:
  - .travis/set-up-ssh.sh

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master