# MAIN
language: php
dist: trusty
sudo: required

# PHP
php:
  - 7.1.9

# SERVICES
services:
  - mysql

# CACHE
cache:
  directories:
    - $HOME/.composer/cache

# ADDONS
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

# INSTALL
install:
  # Init Mysql
  - mysql -u root <<< "CREATE DATABASE IF NOT EXISTS yii2advanced_test COLLATE utf8_unicode_ci CHARACTER SET utf8;"

  # composer
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.4.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

  # codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"

  # setup application
  - ./init --env=Development
  - sed -i s/root/travis/ common/config/main-local.php
  - sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
  - sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

# BEFORE SCRIPT
before_script:
  - php yii_test migrate --interactive=0

# SCRIPT
script:
  - php vendor/bin/codecept run unit models

# BEFORE DEPLOY
before_deploy:
  - .travis/set-up-ssh.sh

# DEPLOY
deploy:
  - provider: script
    skip_cleanup: true
    script: .travis/deploy.sh
    on:
      branch: master